services: 
  irishealth-demo:
    build: .
    image: irishealth-demo:1.0
    container_name: irishealth-demo
    ports:
    # the webserver port
    - "8002:52773"

    # Superserver port
    - 8001:1927
    # HL7 TCP port
    - 8004:44444

    ### Mount durable volume ###
    # volumes:
    # - ./data/durable:/durable

    ### Enable durable SYS (requires durable volume) ###
    # environment:
    # - ISC_DATA_DIRECTORY=/durable/iris_conf.d

    ### Password & License (requires durable volume) ###
    #command:  --key /durable/iris.key --password-file /durable/password.txt


